"""update country model

Revision ID: 206f0fffa28c
Revises: 63c037b0c0f4
Create Date: 2025-03-26 14:50:26.236516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206f0fffa28c'
down_revision: Union[str, None] = '63c037b0c0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'code',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'code',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    # ### end Alembic commands ###
