"""Remove flag to Country

Revision ID: 63c037b0c0f4
Revises: fb5a7c27a884
Create Date: 2025-03-26 14:30:24.640278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c037b0c0f4'
down_revision: Union[str, None] = 'fb5a7c27a884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'flag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('flag', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
