"""new update_1

Revision ID: 6f1f217494b6
Revises: ac93211895e2
Create Date: 2025-02-22 16:56:31.190155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1f217494b6'
down_revision: Union[str, None] = 'ac93211895e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('rate', sa.DECIMAL(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_rates_currency'), 'rates', ['currency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rates_currency'), table_name='rates')
    op.drop_table('rates')
    # ### end Alembic commands ###
