"""setup scale

Revision ID: a04aa33b088c
Revises: 5413759bab0b
Create Date: 2025-02-24 18:20:10.592041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04aa33b088c'
down_revision: Union[str, None] = '5413759bab0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount_sent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'amount_received',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'rate',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('transactions', 'amount_received',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('transactions', 'amount_sent',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
