"""new update_idx

Revision ID: aa14bbefed05
Revises: 6f1f217494b6
Create Date: 2025-02-22 18:26:32.046010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa14bbefed05'
down_revision: Union[str, None] = '6f1f217494b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_currency', 'rates', ['currency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_currency', table_name='rates')
    # ### end Alembic commands ###
