"""modify any field

Revision ID: e510a76cd154
Revises: 79cb40b7d4a8
Create Date: 2025-02-14 16:43:34.084365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e510a76cd154'
down_revision: Union[str, None] = '79cb40b7d4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('countries_currency_code_fkey', 'countries', type_='foreignkey')
    op.create_foreign_key(None, 'countries', 'currencies', ['currency_code'], ['code'], ondelete='CASCADE')
    op.drop_constraint('exchange_rates_base_currency_fkey', 'exchange_rates', type_='foreignkey')
    op.drop_constraint('exchange_rates_target_currency_fkey', 'exchange_rates', type_='foreignkey')
    op.create_foreign_key(None, 'exchange_rates', 'currencies', ['base_currency'], ['code'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exchange_rates', 'currencies', ['target_currency'], ['code'], ondelete='CASCADE')
    op.drop_constraint('fees_base_country_fkey', 'fees', type_='foreignkey')
    op.drop_constraint('fees_target_country_fkey', 'fees', type_='foreignkey')
    op.create_foreign_key(None, 'fees', 'countries', ['base_country'], ['name'], ondelete='CASCADE')
    op.create_foreign_key(None, 'fees', 'countries', ['target_country'], ['name'], ondelete='CASCADE')
    op.drop_constraint('r_payments_country_name_fkey', 'r_payments', type_='foreignkey')
    op.create_foreign_key(None, 'r_payments', 'countries', ['country_name'], ['name'], ondelete='CASCADE')
    op.drop_constraint('s_payments_country_name_fkey', 's_payments', type_='foreignkey')
    op.create_foreign_key(None, 's_payments', 'countries', ['country_name'], ['name'], ondelete='CASCADE')
    op.add_column('transactions', sa.Column('transaction_number', sa.VARCHAR(), nullable=False))
    op.create_unique_constraint(None, 'transactions', ['transaction_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'transaction_number')
    op.drop_constraint(None, 's_payments', type_='foreignkey')
    op.create_foreign_key('s_payments_country_name_fkey', 's_payments', 'countries', ['country_name'], ['name'])
    op.drop_constraint(None, 'r_payments', type_='foreignkey')
    op.create_foreign_key('r_payments_country_name_fkey', 'r_payments', 'countries', ['country_name'], ['name'])
    op.drop_constraint(None, 'fees', type_='foreignkey')
    op.drop_constraint(None, 'fees', type_='foreignkey')
    op.create_foreign_key('fees_target_country_fkey', 'fees', 'countries', ['target_country'], ['name'])
    op.create_foreign_key('fees_base_country_fkey', 'fees', 'countries', ['base_country'], ['name'])
    op.drop_constraint(None, 'exchange_rates', type_='foreignkey')
    op.drop_constraint(None, 'exchange_rates', type_='foreignkey')
    op.create_foreign_key('exchange_rates_target_currency_fkey', 'exchange_rates', 'currencies', ['target_currency'], ['code'])
    op.create_foreign_key('exchange_rates_base_currency_fkey', 'exchange_rates', 'currencies', ['base_currency'], ['code'])
    op.drop_constraint(None, 'countries', type_='foreignkey')
    op.create_foreign_key('countries_currency_code_fkey', 'countries', 'currencies', ['currency_code'], ['code'])
    # ### end Alembic commands ###
