"""new update

Revision ID: e665b7477035
Revises: e510a76cd154
Create Date: 2025-02-21 14:12:22.441383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e665b7477035'
down_revision: Union[str, None] = 'e510a76cd154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'flag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'currencies', ['symbol'])
    op.drop_column('currencies', 'full_name')
    op.add_column('r_payments', sa.Column('method_name', sa.VARCHAR(), nullable=False))
    op.drop_column('r_payments', 'r_name')
    op.add_column('s_payments', sa.Column('method_name', sa.VARCHAR(), nullable=False))
    op.drop_column('s_payments', 's_name')
    op.add_column('transactions', sa.Column('transfer_amount', sa.FLOAT(), nullable=False))
    op.add_column('transactions', sa.Column('receive_amount', sa.FLOAT(), nullable=False))
    op.add_column('transactions', sa.Column('payment_method', sa.VARCHAR(), nullable=False))
    op.drop_column('transactions', 's_pay')
    op.drop_column('transactions', 'r_pay')
    op.drop_column('transactions', 'amount_converted')
    op.drop_column('transactions', 'final_amount')
    op.drop_column('transactions', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('final_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('amount_converted', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('r_pay', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('s_pay', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'receive_amount')
    op.drop_column('transactions', 'transfer_amount')
    op.add_column('s_payments', sa.Column('s_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('s_payments', 'method_name')
    op.add_column('r_payments', sa.Column('r_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('r_payments', 'method_name')
    op.add_column('currencies', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'currencies', type_='unique')
    op.alter_column('countries', 'flag',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
