"""add indexation..

Revision ID: fb5a7c27a884
Revises: eafe87a120de
Create Date: 2025-02-25 12:28:08.790493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5a7c27a884'
down_revision: Union[str, None] = 'eafe87a120de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_base_to', 'fees', ['base', 'to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_base_to', table_name='fees')
    # ### end Alembic commands ###
